import { lstat, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { packageVersion } from "./package.js";

const templatesDirectory = fileURLToPath(new URL("../templates", import.meta.url));
const agentsBlockTemplate = "_AGENTS.block.md";
const agentsStart = "<!-- synod:start -->";
const agentsEnd = "<!-- synod:end -->";
const generatedConfigMarker = "# Generated by Synod.";
const durableStatePrefix = "docs/synod/";

async function pathType(candidate) {
  try {
    const value = await lstat(candidate);
    if (value.isFile()) return "file";
    if (value.isDirectory()) return "directory";
    if (value.isSymbolicLink()) return "symlink";
    return "other";
  } catch (error) {
    if (error.code === "ENOENT") return "missing";
    throw error;
  }
}

async function unsafeAncestor(targetDirectory, targetPath) {
  const relativePath = path.relative(targetDirectory, targetPath);
  if (path.isAbsolute(relativePath) || relativePath === ".." || relativePath.startsWith(`..${path.sep}`)) {
    throw new Error(`Generated path escapes the target directory: ${targetPath}`);
  }

  const segments = relativePath.split(path.sep).filter(Boolean).slice(0, -1);
  let currentPath = targetDirectory;

  for (const segment of segments) {
    currentPath = path.join(currentPath, segment);
    const type = await pathType(currentPath);
    if (type !== "missing" && type !== "directory") {
      return path.relative(targetDirectory, currentPath).split(path.sep).join("/");
    }
  }

  return undefined;
}

async function listTemplateFiles(directory = templatesDirectory, prefix = "") {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const relativePath = path.posix.join(prefix, entry.name);
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...await listTemplateFiles(absolutePath, relativePath));
    } else if (entry.isFile() && entry.name !== agentsBlockTemplate) {
      files.push(relativePath);
    }
  }

  return files;
}

function renderTemplate(content) {
  return content.replaceAll("__SYNOD_VERSION__", packageVersion);
}

function normalizeText(content) {
  return content.replaceAll("\r\n", "\n");
}

function findManagedAgentsBlock(content) {
  const start = content.indexOf(agentsStart);
  const end = content.indexOf(agentsEnd);

  if (start === -1 && end === -1) return null;
  if (start === -1 || end === -1 || end < start) {
    throw new Error("AGENTS.md contains an incomplete Synod managed block.");
  }

  return { start, end: end + agentsEnd.length };
}

function mergeAgentsFile(existing, block, force) {
  const managed = findManagedAgentsBlock(existing);
  if (!managed) {
    const separator = existing.length === 0 || existing.endsWith("\n\n") ? "" : existing.endsWith("\n") ? "\n" : "\n\n";
    return { content: `${existing}${separator}${block}\n`, changed: true };
  }

  const current = existing.slice(managed.start, managed.end);
  const next = block.trimEnd();
  if (normalizeText(current) === normalizeText(next)) {
    return { content: existing, changed: false };
  }
  if (!force) return { conflict: true };

  return {
    content: `${existing.slice(0, managed.start)}${next}${existing.slice(managed.end)}`,
    changed: true
  };
}

async function planAgentsFile(targetDirectory, force) {
  const targetPath = path.join(targetDirectory, "AGENTS.md");
  const block = renderTemplate(await readFile(path.join(templatesDirectory, agentsBlockTemplate), "utf8")).trimEnd();
  if (await unsafeAncestor(targetDirectory, targetPath)) return { path: "AGENTS.md", conflict: true };
  const type = await pathType(targetPath);

  if (type === "directory" || type === "other") return { path: "AGENTS.md", conflict: true };
  const existing = type === "file" ? await readFile(targetPath, "utf8") : "";
  const merged = mergeAgentsFile(existing, block, force);

  if (merged.conflict) return { path: "AGENTS.md", conflict: true };
  if (!merged.changed) return { path: "AGENTS.md", action: "unchanged" };
  return { path: "AGENTS.md", action: type === "missing" ? "create" : "update", content: merged.content };
}

async function planTemplateFile(targetDirectory, relativePath, force) {
  const sourcePath = path.join(templatesDirectory, relativePath);
  const targetPath = path.join(targetDirectory, ...relativePath.split("/"));
  const content = renderTemplate(await readFile(sourcePath, "utf8"));
  if (await unsafeAncestor(targetDirectory, targetPath)) return { path: relativePath, conflict: true };
  const type = await pathType(targetPath);

  if (type === "missing") return { path: relativePath, action: "create", content };
  if (type !== "file") return { path: relativePath, conflict: true };

  const existing = await readFile(targetPath, "utf8");
  if (normalizeText(existing) === normalizeText(content)) {
    return { path: relativePath, action: "unchanged" };
  }

  if (relativePath.startsWith(durableStatePrefix)) {
    return {
      path: relativePath,
      action: "unchanged",
      warning: `Preserved durable project state in ${relativePath}. Synod never overwrites project memory.`
    };
  }

  if (relativePath === ".codex/config.toml" && !existing.startsWith(generatedConfigMarker)) {
    return {
      path: relativePath,
      action: "unchanged",
      warning: "Preserved the existing user-owned .codex/config.toml. Merge Synod model and [agents] defaults manually if desired."
    };
  }

  if (!force) return { path: relativePath, conflict: true };
  return { path: relativePath, action: "update", content };
}

export async function initProject({ directory = ".", dryRun = false, force = false } = {}) {
  const targetDirectory = path.resolve(directory);
  const targetType = await pathType(targetDirectory);
  if (targetType === "missing") throw new Error(`Target directory does not exist: ${targetDirectory}`);
  if (targetType !== "directory") throw new Error(`Target is not a real directory: ${targetDirectory}`);

  const templateFiles = await listTemplateFiles();
  const operations = [await planAgentsFile(targetDirectory, force)];
  for (const relativePath of templateFiles) {
    operations.push(await planTemplateFile(targetDirectory, relativePath, force));
  }

  const conflicts = operations.filter(operation => operation.conflict).map(operation => operation.path);
  const warnings = operations.flatMap(operation => operation.warning ? [operation.warning] : []);

  const result = {
    targetDirectory,
    dryRun,
    created: operations.filter(operation => operation.action === "create").map(operation => operation.path),
    updated: operations.filter(operation => operation.action === "update").map(operation => operation.path),
    unchanged: operations.filter(operation => operation.action === "unchanged").map(operation => operation.path),
    conflicts,
    warnings
  };

  if (dryRun || conflicts.length > 0) return result;

  for (const operation of operations) {
    if (operation.action !== "create" && operation.action !== "update") continue;
    const targetPath = path.join(targetDirectory, ...operation.path.split("/"));
    const unsafePath = await unsafeAncestor(targetDirectory, targetPath);
    if (unsafePath) throw new Error(`Refusing to write through unsafe path: ${unsafePath}`);

    const currentType = await pathType(targetPath);
    const expectedType = operation.action === "create" ? "missing" : "file";
    if (currentType !== expectedType) {
      throw new Error(`Refusing to write changed destination: ${operation.path}`);
    }

    await mkdir(path.dirname(targetPath), { recursive: true });
    await writeFile(targetPath, operation.content, "utf8");
  }

  return result;
}
