import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ERROR_CODES, SynodError } from "./errors.js";
import { packageName } from "./package.js";

export const templatesDirectory = fileURLToPath(new URL("../templates", import.meta.url));
export const agentsStart = "<!-- synod:start -->";
export const agentsEnd = "<!-- synod:end -->";
export const generatedConfigMarker = "# Generated by Synod.";

export function ownershipFor(relativePath) {
  if (relativePath === "AGENTS.md") return "shared";
  if ([".synod/state.json", ".synod/events.jsonl", "docs/synod/STATUS.md"].includes(relativePath)) return "record";
  if (relativePath.startsWith("docs/synod/")) return "user";
  return "synod";
}

async function listFiles(directory = templatesDirectory, prefix = "") {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const relativePath = path.posix.join(prefix, entry.name);
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await listFiles(absolutePath, relativePath));
    else if (entry.isFile() && relativePath !== "_AGENTS.block.md" && relativePath !== ".synod/manifest.json") {
      files.push(relativePath);
    }
  }
  return files;
}

function replacements(version, profile) {
  const roles = profile.roles;
  return {
    __SYNOD_VERSION__: version,
    __SYNOD_COMMAND__: `pnpm dlx ${packageName}@${version}`,
    __SYNOD_PROFILE__: profile.id,
    __SYNOD_SUPERVISOR_MODEL__: roles.supervisor.model,
    __SYNOD_SUPERVISOR_EFFORT__: roles.supervisor.effort,
    __SYNOD_PLAN_EFFORT__: roles.supervisor.planEffort,
    __SYNOD_IMPLEMENTER_MODEL__: roles.implementer.model,
    __SYNOD_IMPLEMENTER_EFFORT__: roles.implementer.effort,
    __SYNOD_EXPLORER_MODEL__: roles.explorer.model,
    __SYNOD_EXPLORER_EFFORT__: roles.explorer.effort,
    __SYNOD_REVIEWER_MODEL__: roles.reviewer.model,
    __SYNOD_REVIEWER_EFFORT__: roles.reviewer.effort,
    __SYNOD_VERIFIER_MODEL__: roles.verifier.model,
    __SYNOD_VERIFIER_EFFORT__: roles.verifier.effort,
    __SYNOD_MECHANICAL_MODEL__: roles.mechanical.model,
    __SYNOD_MECHANICAL_EFFORT__: roles.mechanical.effort
  };
}

export function renderTemplate(content, version, profile) {
  let rendered = content;
  for (const [token, value] of Object.entries(replacements(version, profile))) {
    rendered = rendered.replaceAll(token, value);
  }
  return rendered;
}

export async function loadTemplateSet(version, profile) {
  const files = new Map();
  for (const relativePath of await listFiles()) {
    const content = await readFile(path.join(templatesDirectory, ...relativePath.split("/")), "utf8");
    files.set(relativePath, renderTemplate(content, version, profile));
  }
  const block = renderTemplate(
    await readFile(path.join(templatesDirectory, "_AGENTS.block.md"), "utf8"),
    version,
    profile
  ).trimEnd();
  return { files, agentsBlock: block };
}

export function findManagedAgentsBlocks(content) {
  const markerPattern = /<!-- synod:(start|end) -->/g;
  const blocks = [];
  let openStart;
  let match;
  while ((match = markerPattern.exec(content)) !== null) {
    if (match[1] === "start") {
      if (openStart !== undefined) {
        throw new SynodError(ERROR_CODES.AGENTS_BLOCK_MALFORMED, "AGENTS.md contains nested Synod markers.", {
          details: { path: "AGENTS.md", reason: "nested_start" }
        });
      }
      openStart = match.index;
    } else {
      if (openStart === undefined) {
        throw new SynodError(ERROR_CODES.AGENTS_BLOCK_MALFORMED, "AGENTS.md contains an orphan Synod end marker.", {
          details: { path: "AGENTS.md", reason: "orphan_end" }
        });
      }
      blocks.push({ start: openStart, end: match.index + match[0].length });
      openStart = undefined;
    }
  }
  if (openStart !== undefined) {
    throw new SynodError(ERROR_CODES.AGENTS_BLOCK_MALFORMED, "AGENTS.md contains an incomplete Synod block.", {
      details: { path: "AGENTS.md", reason: "missing_end" }
    });
  }
  return blocks;
}

export function extractManagedAgentsBlock(content) {
  const blocks = findManagedAgentsBlocks(content);
  if (blocks.length !== 1) return { blocks, content: undefined };
  return { blocks, content: content.slice(blocks[0].start, blocks[0].end) };
}

export function agentsBlockSeparator(existing) {
  return existing.length === 0 || existing.endsWith("\n\n") ? "" : existing.endsWith("\n") ? "\n" : "\n\n";
}

export function appendAgentsBlock(existing, block) {
  const separator = agentsBlockSeparator(existing);
  return `${existing}${separator}${block}\n`;
}

export function replaceAgentsBlocks(existing, block) {
  const managedBlocks = findManagedAgentsBlocks(existing);
  if (managedBlocks.length === 0) return appendAgentsBlock(existing, block);
  let content = "";
  let cursor = 0;
  for (const [index, managed] of managedBlocks.entries()) {
    content += existing.slice(cursor, managed.start);
    if (index === 0) content += block;
    cursor = managed.end;
  }
  return content + existing.slice(cursor);
}

export function removeAgentsBlocks(existing, { separatorBefore } = {}) {
  const managedBlocks = findManagedAgentsBlocks(existing);
  let content = existing;
  for (const managed of [...managedBlocks].reverse()) {
    let start = managed.start;
    let end = managed.end;
    if (
      managedBlocks.length === 1
      && separatorBefore !== undefined
      && existing.slice(start - separatorBefore.length, start) === separatorBefore
    ) {
      start -= separatorBefore.length;
    }
    if (existing[end] === "\n") end += 1;
    content = content.slice(0, start) + content.slice(end);
  }
  return content;
}
